### PR TITLE
Bump version to 5.5.1

### PR DESCRIPTION
**Pull request by sbesson**
Following the release of [OME Files 0.5.0](http://www.openmicroscopy.org/2017/12/04/ome-files-0-5-0.html), this PR increments the patch number

See also https://github.com/openmicroscopy/ome-documentation/pull/1819

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Could you also add a NEWS.md block, e.g.

```
5.5.1 (unreleased)
------------------

* No changes

```

which will allow subsequent PRs to add news items in the PRs which introduce them.

**Review by joshmoore — COMMENTED** [review]
This strategy works for me. As I mentioned previously elsewhere, I still also see the value of having a comment in this file

```
+set(release-version "5.5.1") # unreleased
```

in this file as well. Either way, @rleigh-codelibre's `NEWS.md` proposal makes sense.

The only thing I'd add is that if we *omit* the `unreleased` in *both* locations, then there's some potential for releasing without the need for a new PR. Not sure if that's worth it to us.

**Comment by rleigh-codelibre** [comment]
It really depends upon the logistics we want.  If we always have a release date in NEWS.md, then we'll always need a pre-release PR to update that information.

The NEWS.md file also has potential for introducing PR conflicts for PRs which try to add NEWS items.  Easy enough to fix before merging, but might cause problems with our scc merge workflow.  CMake gets around this by having a separate Sphinx file for each introduced change.  https://gitlab.kitware.com/cmake/cmake/tree/master/Help/release/dev for example.

**Comment by sbesson** [comment]
Thanks both, I am not overly worried about the cost of opening a pre-release PR updating only `NEWS.md` and optionally dropping a `# unreleased` suffix, or optionally push these release changes directly to `master` as we do for [Java components](http://docs.openmicroscopy.org/contributing/java-development.html#release-preparation). There are certainly larger bottlenecks that prevent our ability to cut  an OME Files release workflow we want to address first.

Barring vetoes at the upcoming meeting, I propose to push an extra commit with the `unreleased` changes discussed above.

**Comment by rleigh-codelibre** [comment]
Looks fine to me.

**Pull request merged**
