### PR TITLE
Windows header portability checks and fixes

### PR DESCRIPTION
**Pull request by ghost**
The main Windows header `<windows.h>` directly and indirectly defines a large number of macros using common names which conflict with usage in any other code.  This is most problematic in headers.
- undefine and redefine the `min`, `max` and `pascal` macros while processing headers
- extend the header tests by including `<windows.h>` or `<unistd.h>` to ensure that the headers don't conflict with the system headers

Note that the automated header checks cater only for successful inclusion, not that every header feature is functional.  This will catch the most obvious problems, but it will require compilation of code making use of the features while also including `<windows.h>` to discover the more subtle issues.  This is taken care of, albeit not comprehensively, by the `ome-qtwidgets` component.  I'd like to highlight the importance of such testing.  Our own code doesn't need to include these system headers, so we don't ourselves see such issues when everything cleanly compiles.  But this would be a critical bug for an end user who finds themselves unable to use our headers.  While a component such as `ome-qtwidgets` isn't that useful in itself, it's actually quite important in terms of verifying that the API is usable from the point of view of a third party.

---

Testing: This is all catered for with unit tests, so checking the job status will be sufficient.

### CODE REVIEW

**Comment by mtbc** [comment]
Diff looks good to me, see when CI is happy.

**Comment by ghost** [comment]
Note all builds are now green.

**Comment by sbesson** [comment]
Following the implementation of this functionality in OMERO as well, merging this set of PRs. Is there any follow-up for the systematic usage of `ome-qtwidgets` as a high-level component or is everything handled in other PRs?

**Comment by ghost** [comment]
@sbesson If you're referring to building ome-qtwidgets routinely, it's done by the superbuild logic on the appropriate platforms, taken care of by the recent ome-cmake-superbuild jenkins-build script changes.

**Pull request merged**
