### PR TITLE
Split Bio-Formats C++ from bioformats.git

### PR DESCRIPTION
**Pull request by ghost**
This component contains shared infrastructure which requires refactoring to handle the split.
- module path introspection updated to allow other components (one-xml and bioformats) to register paths, and remove hard-coded paths from other components
- this includes picking up a missing commit from 5.1
- correct documentation install paths for use by other components

---

See https://github.com/openmicroscopy/bioformats/pull/2258 for testing instructions

### CODE REVIEW

**Comment by sbesson** [comment]
All steps of https://github.com/openmicroscopy/bioformats/pull/2258#issue-135890218 have been successfully tested. After discussion with @rleigh-dundee and @joshmoore, merging this PR as well as the companion Bio-Formats one.

**Comment by ghost** [comment]
See also https://github.com/ome/ome-files-cpp/pull/1

Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge/90/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/116/ and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/133/

**Comment by sbesson** [comment]
Was the comment above meant to be added to https://github.com/ome/ome-cmake-superbuild/pull/41 ?

**Comment by ghost** [comment]
Oh, yes

**Pull request merged**
