### PR TITLE
cmake: Remove find modules distributed with CMake

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
The aim of this is to allow rebuilds when new versions of Boost and other dependencies are released, without having to update and re-release all source components.  We can instead use the system copy with an updated cmake, or the version provided by the superbuild.  This will both reduce the ongoing maintenance overhead and make rebuilding more flexible.

Testing: All builds should be green.

### CODE REVIEW

**Comment by joshmoore** [comment]
Summarizing a distributed discussion with @sbesson and @rleigh-codelibre:

 * A Boost release just after OME Files 0.4.0 broke homebrew. This set of PRs is an attempt to reduce that type of issue.
 * This is the last blocking item from https://trello.com/b/UDHFxFD4/ome-files-050
 * All other open cards have been pushed to https://trello.com/b/LX6zHrGZ/ome-files-060

**Comment by rleigh-codelibre** [comment]
Note, was green in

- https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-win-superbuild/813/
- https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-superbuild/802/
- https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge/733/
- https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-docs/542/

Windows is currently red due to a cache path problem in another PR, but the changes in this PR are OK.

**Comment by dgault** [comment]
Only changes in this and associated PR's are the removal of FindModules and PlatformChecks. Builds are green with these changes (Windows have an unrelated problem in the most recent builds). 

This PR and the associated PR's below look good to merge:
https://github.com/ome/ome-model/pull/59 
https://github.com/ome/ome-files-cpp/pull/88
https://github.com/ome/ome-qtwidgets/pull/33
https://github.com/openmicroscopy/ome-files-performance/pull/58

**Comment by joshmoore** [comment]
All builds green (again) this morning.

**Pull request merged**
