### PR TITLE
source-archive: Set GitVersion mtime

### PR DESCRIPTION
**Pull request by ghost**
Correct  timestamp

```
scripts/source-archive --release=test --target=/tmp --tag=HEAD
```

Check `cmake/GitVersion.cmake` in the tar archive.  The version will also be the current date and time, rather than 1-1-1970.

### CODE REVIEW

**Comment by sbesson** [comment]
Tested using the description in the PR. The date of the generated `GitVersion.cmake` is now set to the creation time as expected. As said in https://github.com/ome/ome-cmake-superbuild/pull/49#discussion_r57437340, can we add a reference to the ninja issue in the script explaining this line addition?

**Comment by ghost** [comment]
@sbesson I'm not convinced that a comment in the script itself has any value--it should always have had an mtime set, and so a comment here regarding ninja isn't particularly useful to have for the future.  I can certainly add it to the commit message if wanted?

**Comment by sbesson** [comment]
@rleigh-dundee: if we had the infrastructure and time, I would like to have a corresponding unit test so that we catch any regression in future amendments of this release script. In this case, the unit test would also suffice as documentation. In the meantime, I would still add either an inline comment or amend the commit message as you propose so that we remember somewhere that not overriding the default zero value of `mtime` should be considered as a blocker to the source release.

**Comment by ghost** [comment]
@sbesson All PRs updated with an appropriate commit message.  We'll also get regular testing with the source build job once I've tweaked it.

**Comment by sbesson** [comment]
Retested with the last version of the commit. Works as expected.

**Pull request merged**
