### PR TITLE
Embed release version directly in CMakeLists.txt

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See [trello card](https://trello.com/c/vMoR9wUQ/65-release-ome-common-cpp).  Don't get the release version from git.  Continue to use git to set a `-DEV-shortrev` suffix for informational purposes, but don't use git tags when running cmake.

Remove the source archive script.  Update the cmake `source-archive` target to generate a source release directly (this is how the script was invoked by the superbuild).  For actual releasing, we'll run `git archive` directly from the release tag; the script isn't needed for that--it only existed to do the version embedding.

Testing:

- Since this is a leaf dependency, you can build it standalone outside the superbuild for testing
- Check the version is correctly set when running cmake (check build log).
- Check `lib/ome/common/OMECommonConfigVersion.cmake` has the correct package version
- Run `cmake --build . --target source-archive`; it should create a source archive (tar and zip).
- Unpack the archive and try building it.

CI:

- Update OME-COMMON-CPP-release to run `git archive` directly with the release tag.

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge/BUILD_TYPE=Debug,node=snipe/463. Marking as `breaking`

**Comment by rleigh-codelibre** [comment]
@sbesson Should be OK to come out of breaking now, it's passing there.

**Comment by simleo** [comment]
* While running cmake:

```
[...]
-- Configuring OME Common C++ (ome-common 5.3.3-DEV-1288bbf)
[...]
```

* `lib/ome/common/OMECommonConfigVersion.cmake`:

```
[...]
`set(PACKAGE_VERSION "5.3.3")`
[...]
```

* `cmake --build . --target source-archive` created:

```
ome-common-cpp-5.3.3-DEV-1288bbf.tar.xz
ome-common-cpp-5.3.3-DEV-1288bbf.zip
```

* Unpacked both archives and built `libome-common.5.3.3`.

I have also tried rebuilding the Docker image for ome-files-py with `RUN git clone --branch='release-version' https://github.com/rleigh-codelibre/ome-common-cpp.git` and everything went fine up to and including the unit tests.

**Comment by sbesson** [comment]
Thanks @simleo. Re CI adjustement, the core part of the current release job is currently executing

```
scc tag-release $RELEASE --no-ask --push --prefix=v
cd src
./scripts/source-archive --release=${PREFIX} --target=${WORKSPACE}/artefacts/source --tag=v${RELEASE}
```

If I understand correctly, the tag becomes now purely informative as long as the `git archive` command is used. Alternatively, `cmake --build . --target source-archive` should be usable as long as an annotated tag matching `release-version` has been created first? @simleo did you test this workflow as well (annotated tag + cmake target). Should the latter be used for consistency and since the `cmake` target already wraps the required Git commands?

In terms of release workflow, this proposal means a version bump PR will be open prior to any C++ source release, is that correct?

**Comment by simleo** [comment]
I've tried adding a bogus tag `git tag -a v9.9.9`: this is ignored both when running cmake directly on the git repo and from the archive's contents after `cmake --build . --target source-archive`, i.e., the version tag is set to the embedded value of `5.3.3`.

**Comment by rleigh-codelibre** [comment]
For releasing, this script is irrelevant--releasing uses the signed release tag only and not this script.  This is purely to not break the existing workflow and to provide the source corresponding to the binary build on the CI side.  So you can get the source corresponding to the merge for the binary archives after the scc branch has been overwritten.

This script does not require any tags; it's simply archiving HEAD with the hardcoded version from CMakeLists.txt plus any -DEV+git-hash suffix.

For the release workflow, the existing release job does the tagging, and then it will just run "git archive" itself; this PR is irrelevant for that process.

The only change relevant to the release process here is the hardcoding of the release version in maven style.

**Pull request merged**
