### PR TITLE
cmake: Remove global OME configuration script

### PR DESCRIPTION
**Pull request by ghost**
Users of the libraries will need to use the individual configuration scripts for each component, i.e. OMECommon, OMEXML, OMEFiles, OMEQtWidgets rather than "OME".  This is because they don't have a common version, so having a central configuration with a single version number doesn't really work, and wasn't used in practice anyway--the few remaining instances are dropped in companion PRs.

See https://trello.com/c/uIDhDZhS/14-component-versioning

The major change is the dropping of the "OME" global package in favour of the separate per-component packages.

We also update the configuration export in each component, to match the changes made to the "bzip2" patch after upstream review.  This significantly improves the correctness and robustness of the CMake configuration we provide.  This will greatly improve the ease of use and experience end users have who wish to use these libraries.

---

Testing: These changes are tested by the CI jobs, since this configuration information is consumed by the dependent components.

### CODE REVIEW

**Comment by joshmoore** [comment]
To the extent that I understand them, the changes make sense. Certainly the reasoning

> Users of the libraries will need to use the individual configuration scripts for each component, i.e. OMECommon, OMEXML, OMEFiles, OMEQtWidgets rather than "OME". This is because they don't have a common version,

makes perfect sense. Perhaps my only concern since I don't fully understand the changes is: what's the impact on the "end user"? i.e. this likely counts as a breaking build change, right? And if so, does there need to be any change to a README or similar for someone who might be looking to make the next such component?

**Comment by ghost** [comment]
If as an end user you were using find_package(OME COMPONENTS XML Files ...) you'll now need to use find_package(OMEXML), find_package(OMEFiles).  It's certainly something to put in the release notes, though this stuff was in its infancy with the initial 0.1 release, so this is really the "working" version.

This is something I'll be adding to the super-build in subsequent PRs--we can now make the examples build using the superbuild, which means we can document this directly in OME files with the CMakeLists.txt files for the examples using the correct form for building as an end user rather than in-tree, and we can source this in the docs as the recommended way to do things.

**Comment by sbesson** [comment]
Looking at the four PRs, the set of versioning changes also make sense to me, worth documenting in the release notes and all the builds are green. Is there a corresponding section in the Sphinx documentation where the `find_package()` behavior should be described as well? Also do the PRs need to be merged before you can open your ome-cmake-superbuild PR?

**Comment by ghost** [comment]
The PRs certainly need merging as a set.  Regarding the documentation, this will go into the tutorial material in ome-files, but since that will require changes both to the examples, documentation and to the superbuild, I'd like that as a followup step once these PRs and the docs PRs are merged.

**Pull request merged**
