### PR TITLE
Add Xalan-C support (basic transforms)

### PR DESCRIPTION
**Pull request by ghost**
- Find XercesC with cmake
- Link with XercesC
- Export XercesC dependency in exported configuration
- Add wrapper for initialisation and cleanup, with mutex
- Add mutex to Xalan platform wrapper as well, since neither are thread-safe
- Add basic test for initialisation and cleanup (also tests Xerces interaction)
- Add class for transforms, with unit tests to test basic transforms and failure cases in the XSL and XML input

Note: `FindXalanC.cmake` is already reviewed and merged by upstream CMake.

---

Testing:
- check jobs are green; configuration, compiling or linking will fail if there's a problem.
- in particular the new Xalan Platform and Transform tests should all pass.
- check `test/ome-common/data/18x24y5z5t2c8b-text-2013-expected.ome` is a valid upgraded file from `test/ome-common/data/18x24y5z5t2c8b-text.ome`
- check `test/ome-common/data/2012-06-to-2013-06-invalid.xsl` is an invalid transform (it's `test/ome-common/data/2012-06-to-2013-06.xsl` with some malformed elements and broken XSL logic); the only purpose is to trigger test failure cases

### CODE REVIEW

**Comment by ghost** [comment]
Note http://xerces-c-users.markmail.org/search/?q=#query:+page:1+mid:6mfruqsaw3iiheeh+state:results for more details about the perch failure.  It's likely not FreeBSD-specific, but related to exactly how Xerces/Xalan are compiled, which has implications for the superbuild.  For the time being, I built Xerces with ICU, which will get the builds green again, but we will need to understand what's going on to be sure it won't happen on other platforms or in the superbuild.

**Comment by ghost** [comment]
https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge/46/console is now green after I fixed up the xerces build on perch to use icu.  Our code here in this PR is correct.  The issue is with xerces/xalan.

If Xalan and Xerces prove untrustworthy, we can always replace one or both with libxsltproc and libxml2 at a future point.  We originally used the former due to the use of some esoteric xsl transform functions which weren't supported by libxslt, but I think they have subsequently been added.  That was the consideration three years ago anyway.  Now I have a clear idea of the exact usage of the XML and XSLT functionality in the codebase, replacing both is definitely an option--we aren't yet at the point where we are tied into them.

https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-superbuild/74/ is green and https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/87/ is green.

**Comment by sbesson** [comment]
After migrating to a node with the corresponding dependencies, the [source generation job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-generated-sources/) is back to normal. Changes look sensible. Today, https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/93/ had 9 failures related to `xalan`

```
05:55:52 18: [  FAILED  ] 9 tests, listed below:
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/0.TransformApply, where TypeParam = struct TestTypes<class boost::filesystem::path,class boost::filesystem::path>
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/1.TransformApply, where TypeParam = struct TestTypes<class std::basic_istream<char,struct std::char_traits<char> >,class boost::filesystem::path>
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/2.TransformApply, where TypeParam = struct TestTypes<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class boost::filesystem::path>
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/3.TransformApply, where TypeParam = struct TestTypes<class boost::filesystem::path,class std::basic_ostream<char,struct std::char_traits<char> > >
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/4.TransformApply, where TypeParam = struct TestTypes<class std::basic_istream<char,struct std::char_traits<char> >,class std::basic_ostream<char,struct std::char_traits<char> > >
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/5.TransformApply, where TypeParam = struct TestTypes<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_ostream<char,struct std::char_traits<char> > >
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/6.TransformApply, where TypeParam = struct TestTypes<class boost::filesystem::path,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/7.TransformApply, where TypeParam = struct TestTypes<class std::basic_istream<char,struct std::char_traits<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >
05:55:52 18: [  FAILED  ] XalanTransformTypes/XalanTest/8.TransformApply, where TypeParam = struct TestTypes<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >
```

**Comment by ghost** [comment]
@sbesson This is due to it replacing LF with CRLF in the transformed output, which makes the comparison fail.  The actual transform is working fine.  We'll need to either stop it adding CRs, or manually add them in the expected text so the comparison succeeds.

**Comment by sbesson** [comment]
Thanks, this certainly matches the detailed console log. What are your thoughts about the correct way to handle this line endings? The fact that Windows will generate CRLF by default sounds like a fair assumption to me. Are there ways to preprocess the expected text in the test itself to replace line endings depending on the platform?

**Comment by ghost** [comment]
Just need to loop over the string's characters and replace by hand; I need to check if the `XALAN_NEWLINE_IS_CRLF` macro is available to us to control this behaviour.

**Comment by ghost** [comment]
@sbesson The latest commit fixes the newlines and allows the comparison to succeed.  I'll restart the jobs to test this.

**Comment by ghost** [comment]
@sbesson Green in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-merge-win-superbuild/94/console

**Comment by sbesson** [comment]
Thanks, waiting for the Linux builds to complete before merging this. Should https://github.com/openmicroscopy/bioformats/issues/2192 be merged as well ?

**Comment by ghost** [comment]
@sbesson Yes, they will need merging together.  The bioformats one is needed to be able to consume the ome-common exported configuration.

**Comment by sbesson** [comment]
Looking at the non Windows builds,
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge-superbuild/83/ passed for all platforms (the snipe error is unrelated to this PR).
- https://ci.openmicroscopy.org/job/BIOFORMATS-CPP-DEV-merge/55 passed for all platforms except FreeBSD where one of the transform tests fails with the following 
  
  ```
  17:11:15 18: Assertion failed: (theInstance->m_referenceCount < UINT_MAX), function addReference, file /usr/ports/textproc/xalan-c/work/xalan-c-1.11/c/src/xalanc/PlatformSupport/XalanReferenceCountedObject.cpp, line 55.
  17:11:15 18: Testing transform of path to path using "/usr/local/opt/hudson/workspace/BIOFORMATS-CPP-DEV-merge/BUILD_TYPE/Debug/node/perch/ome-common-cpp/test/ome-common/data/18x24y5z5t2c8b-text.ome"and "/usr/local/opt/hudson/workspace/BIOFORMATS-CPP-DEV-merge/BUILD_TYPE/Debug/node/perch/ome-common-cpp/test/ome-common/data/2012-06-to-2013-06.xsl"
  ```

**Comment by ghost** [comment]
@sbesson Look like perch is unhappy; fails for me if Xerces is built with ICU (perch) or without (my system), and it segfaults in different places if I run in a debugger, which suggests that there's a real bug in our code somewhere which we need to find.  I would hold off merging until we've identified it.  In the meantime I'll work on the bioformats part which depends upon this.

**Comment by ghost** [comment]
Note xsd-fu failure in https://ci.openmicroscopy.org/view/DEV/job/BIOFORMATS-CPP-DEV-breaking/BUILD_TYPE=Debug,node=cod/2/console

**Comment by sbesson** [comment]
Apart from the perch failures, tests are green on all platforms. Merging this PR and the companion Bio-Formats PR to unlock the rest of the transforms work for M1. As proposed yesterday, let's remove/disable FreeBSD from the testing matrix and add a card for the failure investigation.

**Pull request merged**
