### PR TITLE
Boost 1.53 revert

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See https://trello.com/c/YJBB1cOA/11-centos-7-platform-support

Not for merging at this point.

### CODE REVIEW

**Comment by sbesson** [comment]
See https://hub.docker.com/r/snoopycrimecop/ome-files-cpp-c7/builds/bv8qx8ruqcdkxbg2subugic/ for the build log of the merge OME Files components on a CentOS7 image with the `epel` repository installed.

All tests are passing. Finished a first round of manual testing using the usual scenario with a sample multi-file OME-TIFF (see [omefiles_c7_log.txt](https://github.com/ome/ome-common-cpp/files/1267358/omefiles_c7_log.txt)).

Next testing steps:
- look into enabling qtwidgets into the build
- run the tests against the whole set of OME-TIFF samples

**Comment by sbesson** [comment]
Finished the functional testing against all sample OME-TIFF files:

```
[sbesson@ome-c6220-1-4 ~]$ docker pull snoopycrimecop/ome-files-cpp-c7:master_merge_daily
master_merge_daily: Pulling from snoopycrimecop/ome-files-cpp-c7
74f0853ba93b: Already exists 
7a349f84ad32: Pull complete 
0569dc34a1af: Pull complete 
49c031616230: Pull complete 
64a5862e0831: Pull complete 
285ad9293e0c: Pull complete 
070d3cde39c6: Pull complete 
3a6bcd00e63f: Pull complete 
36c757872b8f: Pull complete 
f3555286ce07: Pull complete 
8b1a6b476536: Pull complete 
6623d9745f7a: Pull complete 
a028e800d733: Pull complete 
a98c61d9dce2: Pull complete 
a6c6a7c2533f: Pull complete 
2e8abbe89704: Pull complete 
c299a0f79694: Pull complete 
54b78c3d4d19: Pull complete 
Digest: sha256:ab80546d8d99b6b21a0304b0b6a11d92376ec147aac091e910473a97e3cd1f2a
Status: Downloaded newer image for snoopycrimecop/ome-files-cpp-c7:master_merge_daily
[sbesson@ome-c6220-1-4 ~]$ docker run --rm -it -v /ome/:/ome/ snoopycrimecop/ome-files-cpp-c7:master_merge_daily
[root@24105f5fce5c build]# (for pat in "*.tif" "*.tiff" "*.tf2" "*.tf8" "*.btf" "*.companion.ome"; do find /ome/data_repo/curated/ome-tiff/ome-schemas/ -name "$pat"; done) | while read f; do echo "TEST READ: $f"; if ome-files info "$f" ; then echo "**SUCCESS** $f" ; else echo "**FAIL**: $f" ; fi ; done
TEST READ: /ome/data_repo/curated/ome-tiff/ome-schemas/2003-FC/single-channel.ome.tif
...
```

**Comment by sbesson** [comment]
In summary of the builds and functional testing, the changes above all make sense.
While keeping in mind the mid-term maintainability concerns raised in https://trello.com/c/YJBB1cOA/11-centos-7-platform-support, there is definitely some added value to bringing CentOS7 to the same level of platform support  as we currently do for Ubuntu 16.04 including promoting this change on the landing pages, providing Docker builds etc. Next step as discussed today will be to enable the usage of `devtoolset-4` in these platform builds to test the OME Files Python bindings.

As this PR and its companion still have `Not for merging at this point` in their description, is there any anything else to consider or are we ready to include this set of PRs?

**Comment by rleigh-codelibre** [comment]
We need devtoolset-4 on cowfish to add this to the platform build job.  Though if ome-files-py isn't being built that should be possible to skip for now.

We also need all the prerequisites from EPEL installing on cowfish.  And these all need documenting in the superbuild, along with the updated prerequisite version of Boost.

**Comment by sbesson** [comment]
Agreed on looking into `devtoolset-4` and EPEL on our CI platforms as a follow-up of this work, I will get this merged and record the documentation tasks mentioned in https://github.com/ome/ome-common-cpp/pull/49#issuecomment-327540911.

Re infrastructure, my understanding from Wednesday's sysadmin conversation and https://github.com/openmicroscopy/infrastructure/pull/272#issuecomment-327477134 is that we have two options:

- either we review  and expand the the `ci_v1` playbooks  used to create `cowfish`
- or we use these new requirements to drive the development of the `ci_v2` playbooks to create a C7 node.

It would be good to have a discussion at the next sysadmin meeting to discuss which route we want to follow and this probably includes discussing a proposal with the next steps. Immediately, we can start enabling `devtoolset-4` in the C7 Docker builds and consume these in `ome-files-py` as we are doing currently with Ubuntu 16.04.

**Pull request merged**
