### PR TITLE
Add source-archive script and cmake SourceArchive helper

### PR DESCRIPTION
**Pull request by ghost**
Add script to create source archive.  Tested by the superbuild.

The release job will run the script as done below.  If this approach is OK, we'll extend this to ome-files-cpp and ome-cmake-superbuild as well.  Later on, we can reimplement this directly in cmake without python being needed (I already have this done for my own projects).

See also: https://github.com/ome/ome-cmake-superbuild/pull/44

---

Testing:

Run

```
./scripts/source-archive --release=ome-common --target=/tmp --tag=HEAD
```

to get a source release (tar.xz and zip) in /tmp.  If you tag the repo, you can use the release tag and get a non-development (-DEV suffix) source release.

### CODE REVIEW

**Comment by joshmoore** [comment]
Initial glance looks good, @rleigh-dundee. Will this (in cmake or python) be able to live in one location and be used across all repos? And if so, in which one?

**Comment by ghost** [comment]
@joshmoore Not at present.  There's no way to share stuff between builds since they are intentionally independent repositories.  We could look at installing them in a location where downstream builds could pick them up, but that's going to be overly complex and fragile, so given the choice I'd go for duplicating the tiny bit of support code since it will avoid a whole bunch of other (worse) problems.

**Comment by joshmoore** [comment]
Downloads generally make sense:

```
/tmp/of-sources $ diff -rs platform superbuild/
Only in superbuild/sources: Genshi-0.7.tar.gz
Only in superbuild/sources: Jinja2-2.7.3.tar.gz
Only in superbuild/sources: MarkupSafe-0.23.tar.gz
Only in superbuild/sources: Pygments-2.0.2.tar.gz
Only in superbuild/sources: Sphinx-1.2.3.tar.gz
Only in superbuild/sources: boost_1_60_0.tar.bz2
Only in superbuild/sources: bzip2-1.0.6.tar.gz
Only in superbuild/sources: docutils-0.12.tar.gz
Only in superbuild/sources: icu4c-55_1-src.tgz
Only in superbuild/sources: libpng-1.6.21.tar.xz
Files platform/sources/ome-common-cpp-5.2.0-m0-63-gada5795-DEV.tar.xz and superbuild/sources/ome-common-cpp-5.2.0-m0-63-gada5795-DEV.tar.xz are identical
Binary files platform/sources/ome-common-cpp-5.2.0-m0-63-gada5795-DEV.zip and superbuild/sources/ome-common-cpp-5.2.0-m0-63-gada5795-DEV.zip differ
Files platform/sources/release-1.7.0.tar.gz and superbuild/sources/release-1.7.0.tar.gz are identical
Only in superbuild/sources: setuptools-18.3.2.tar.gz
Only in superbuild/sources: tiff-4.0.6.tar.gz
Only in superbuild/sources: xalan_c-1.11-src.tar.gz
Only in superbuild/sources: xerces-c-3.1.3.tar.xz
Only in superbuild/sources: zlib-1.2.8.tar.xz
```

The diffs in the 2 zip files are due to the format. Unpacking and diff'ing the contents show them identical. Same for the zip & the xz:

```
tmp/of-sources $ diff -r superbuild_zip/ superbuild_xz/
/tmp/of-sources $ diff -r superbuild_zip/ platform_zip/
/tmp/of-sources $
```

The `release-1.7.0` name is missing "googletest", but I assume it's been like this for a while. Worth a later TODO?

> @joshmoore There's no way to share stuff between builds since they are intentionally independent repositories. We could look at installing them in a location where downstream builds could pick them up, but that's going to be overly complex and fragile, so given the choice I'd go for duplicating the tiny bit of support code since it will avoid a whole bunch of other (worse) problems.

(For anyone reading along, cF. `source-archive` with https://github.com/openmicroscopy/bioformats/blob/v5.1.8/tools/source-archive.py)

For the moment, let's go with this, but I'm skeptical that we can get away from having the infrastructure for sharing some build tools/scripts/components between the repos. I'd very much like to prevent the kind of situation we had with gtest where resources are copied into multiple repositories only to be removed because they are a burden to maintain.

**Comment by ghost** [comment]
The googletest issue isn't new.  We need a way to download with a better name, but this isn't directly exposed via the ExternalProject_Add interface; if there's a way to specify this via the URL then it's fixable, otherwise it's limited to the behaviour of libcurl internally.  We discussed putting each component in a subdirectory as a workaround, but I've not done this yet.

For the sharing of stuff between the repos, as I said it's _possible_ with some effort to put things into an installed location.  But the benefits of sharing a handful of scripts has a cost in the maintenance burden of the added infrastructure, the fragility and complexity of all the downstream components detecting and finding this stuff, and the reduced flexibility in building and using our stuff.  It's not as black and white as "duplication == bad".  If people want to embed our code in a larger Visual Studio solution for example, we're going to make that a complete nightmare to accomplish by adding a baroque and over complex tight coupling between the components in this respect.  Having clean separation between the decoupled components is more important than duplicating a few scripts.

Edit: Note that sharing the scripts would also tightly couple the released components, making it impossible to make an incompatible change to a script in ome-common without updating and releasing _all_ dependent components at the same time.  This would obviate one of the key goals of decoupling--being able to independently release the different components--since the sharing effectively re-introduces a tight coupling.

**Comment by joshmoore** [comment]
> Edit: Note that sharing the scripts would also tightly couple the released components, making it impossible to make an incompatible change to a script in ome-common without updating and releasing all dependent components at the same time. This would obviate one of the key goals of decoupling--being able to independently release the different components--since the sharing effectively re-introduces a tight coupling.

I think we're thinking of these fundamentally differently. For me, these scripts are themselves an artifact which should be versioned and re-usable. If a change (breaking or otherwise) is needed, then you'd release that (i.e. bump the version) and refer to it in projects which depend on it. That would give us one mechanism across the board for dealing with breakages. There will definitely be issues (as there are with any strategy), but having that strictness would likely force us to be more careful and I'd hope make the overall process more understandable to those of us trying to follow along.

**Comment by ghost** [comment]
@joshmoore I can see what you are saying, but the logistics are fundamentally difficult and you don't see projects doing this for a good reason.  It's like a Java project wanting to use an ant build file from another when all it has is the jar of the build--logistically impossible.  The only way to manage this is for ome-common to install the stuff the downstream projects need, but that's a very ugly thing to be doing, and it's worse than duplicating the script.  We already duplicate some of the cmake scripts; we can't really install these either--they would conflict with the cmake-provided ones.

Pondering this a bit more, the release jobs need to run the script to generate the release source archives.  They work with a single repository, so as you can see in https://ci.openmicroscopy.org/view/Files-DEV/job/OME-COMMON-CPP-release/  Since this occurs in the absence of any of the other repositories, making this work in e.g. the ome-files release job without running the build to install the script or manually juggling with files in multiple repos in the release job is going to greatly complicate things.  Really, just copying it vastly simplifies the logistics.  It's just a support script.

This won't be resolved in this set of PRs--if we do want to remove the duplication--and I strongly advise against it--it will require a lot more work to the cmake supporting infrastructure which will need doing separately.

If we could merge this, then we can start testing the above release job.

**Comment by joshmoore** [comment]
> ... It's like a Java project wanting to use an ant build file from another when all it has is the jar of the build--logistically impossible.

I would argue that this is trying to have a maven-plugin rather than an ant build file.

> The only way to manage...

I would argue that as talented as we all our we could come up with more than one suboptimal solution... :smile:

> Really, just copying it vastly simplifies the logistics. It's just a support script.

For the moment, it's "just" a script. But this isn't the first time this issue has come up. We've copied things around before. So yes, let's merge and get these in, but as a design goal, I think we will need to come back to this.

> This won't be resolved in this set of PRs ... it will require a lot more work to the cmake supporting infrastructure which will need doing separately.
> 
> If we could merge this, then we can start testing the above release job.

Agreed. Cheers.

**Pull request merged**
