### PR TITLE
common: units: Add rankine conversions for celsius and fahrenheit

### PR DESCRIPTION
**Pull request by ghost**
Minor addition to the existing units support.  While rankine-kelvin conversion was supported, rankine-celsius and rankine-fahrenheit were not (and are required for the model units support).  Add the conversions, plus unit tests.

---

Testing:
- check unit tests pass (jobs are green)
- verify conversions with e.g. https://www.google.co.uk/webhp?q=convert%20rankine%20to%20fahrenheit (this allows all needed conversions)

### CODE REVIEW

**Comment by rleigh-dundee** [comment]
--breaking
So it's usable with the other related PRs; it's not *actually* breaking.

**Comment by dgault** [comment]
Im not an expert on how the BOOST_UNITS_DEFINE_CONVERSION_FACTOR and BOOST_UNITS_DEFINE_CONVERSION_OFFSET are applied so I could be wrong here.

From googling the offset from celsius to rankine at 0 is -273.15
However the formula Im being given for conversion is:
T(°C) = (T(°R) - 491.67) × 5/9

Should the BOOST_UNITS_DEFINE_CONVERSION_OFFSET we use be the offset at 0 or should it be the offset applied before the conversion factor, in which case should it be -491.67?

**Comment by ghost** [comment]
@dgault This is a straightforward `y = mx + c` equation, i.e. `T2 = (T1 * factor) + offset`.  If you look at `boost/units/base_units/temperature/conversions.hpp` you can verify this with e.g. the °C to °F conversion, where factor = 9.0/5.0 and offset is 32.

50°C = 122°F = 50 \* 9.0/5.0 + 32

So the offset is effectively applied _after_ the conversion factor.  Note we verify the correctness with the unit test data, where we precalculate the results and verify that the code matches this.

°R to °C: factor = 5.0/9.0, offset = -273.15
  500°R = 4.62778°C = 500 \* 5.0/9.0 -273.15

°R to °F: factor = 1 (no change in scale), offset = -459.67
  459.67°R = 0°F = 459.67 \* 1 - 459.67

I hope that all makes sense.  This should all be validated by the unit tests, so verifying that the unit test data is correct should be sufficient here.  I.e. that the numbers in https://github.com/ome/ome-common-cpp/pull/17/files#diff-fdbf7089dda9efb6302a28cac8d2045bR658 when plugged into a converter like https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=convert%20rankine%20to%20fahrenheit give the same results.

**Comment by dgault** [comment]
Yep, that all makes perfect sense and the numbers in the unit test do check out. It was just a question on if the offset T2 = (T1 \* factor) + offset or T2 = (T1 + offset) \* factor

Im happy that it is being applied correctly and everything looks good.

**Pull request merged**
